default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: anota_development

test:
  <<: *default
  database: anota_test

production:
  primary:
    <<: *default
    database: anota_production
  cache:
    <<: *default
    database: anota_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: anota_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: anota_production
    migrations_paths: db/cable_migrate
